x-common-env: &common-env
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  TELEGRAM_WEBHOOK_TOKEN: ${TELEGRAM_WEBHOOK_TOKEN}

services:
  migrate:
    image: ${DOCKER_USERNAME}/kw-app:latest
    command: flask db upgrade
    environment:
      FLASK_APP: app
      <<: *common-env
    restart: "no"
    networks:
      - default

  app:
    image: ${DOCKER_USERNAME}/kw-app:latest
    container_name: app
    expose:
      - "5000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      FLASK_APP: app
      <<: *common-env
    depends_on:
      - migrate
    restart: always
    networks:
      - default

  nginx:
    image: ${DOCKER_USERNAME}/kw-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    restart: always
    networks:
      - default

networks:
  default:
    name: kw-network
