# Generated by Django 5.2.16 on 2026-07-27 17:17

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blog", "0003_alter_revalidationevent_previous_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=320)),
                ("canonical_email", models.CharField(editable=False, max_length=320)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending confirmation"),
                            ("active", "Active"),
                            ("unsubscribed", "Unsubscribed"),
                            ("suppressed", "Suppressed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmation_sent_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("suppressed_at", models.DateTimeField(blank=True, null=True)),
                ("confirmation_token_version", models.PositiveIntegerField(default=1)),
                ("unsubscribe_token_version", models.PositiveIntegerField(default=1)),
                ("suppression_reason", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["status", "confirmed_at", "id"], name="subscriptions_audience_idx"
                    ),
                    models.Index(fields=["created_at", "id"], name="subscriptions_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("canonical_email"),
                        name="subscriptions_unique_canonical_email_ci",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("confirmed_at__isnull", True),
                                ("status", "pending"),
                                ("suppressed_at__isnull", True),
                                ("suppression_reason", ""),
                                ("unsubscribed_at__isnull", True),
                            ),
                            models.Q(
                                ("confirmed_at__isnull", False),
                                ("status", "active"),
                                ("suppressed_at__isnull", True),
                                ("suppression_reason", ""),
                                ("unsubscribed_at__isnull", True),
                            ),
                            models.Q(
                                ("status", "unsubscribed"),
                                ("suppressed_at__isnull", True),
                                ("suppression_reason", ""),
                                ("unsubscribed_at__isnull", False),
                            ),
                            models.Q(
                                ("status", "suppressed"),
                                ("suppressed_at__isnull", False),
                                ("unsubscribed_at__isnull", True),
                                models.Q(("suppression_reason", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="subscriptions_subscriber_lifecycle_shape",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("confirmation", "Subscription confirmation"),
                            ("publication", "New publication"),
                        ],
                        max_length=20,
                    ),
                ),
                ("audience_cutoff", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "credential_version",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("delivered", "Delivered to provider"),
                            ("failed", "Terminal failure"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField()),
                ("processing_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("idempotency_key", models.CharField(editable=False, max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_outbox_events",
                        to="blog.blogpostpage",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_events",
                        to="subscriptions.subscriber",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="EmailDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Accepted by provider"),
                            ("delivered", "Delivered"),
                            ("bounced", "Bounced"),
                            ("complained", "Complained"),
                            ("failed", "Terminal failure"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField()),
                ("processing_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("provider_created_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("bounced_at", models.DateTimeField(blank=True, null=True)),
                ("complained_at", models.DateTimeField(blank=True, null=True)),
                ("bounce_type", models.CharField(blank=True, max_length=64)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="subscriptions.emailoutbox",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="subscriptions.subscriber",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SubscriptionRateLimitBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("subscribe_email", "Subscribe email"),
                            ("subscribe_ip", "Subscribe IP"),
                            ("confirm_ip", "Confirm IP"),
                        ],
                        max_length=24,
                    ),
                ),
                ("key_hash", models.CharField(max_length=64)),
                ("window_started_at", models.DateTimeField()),
                ("request_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "key_hash"), name="subscriptions_unique_rate_bucket"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailWebhookEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("provider", models.CharField(default="resend", editable=False, max_length=32)),
                ("event_id", models.CharField(max_length=255)),
                ("event_type", models.CharField(max_length=80)),
                ("provider_occurred_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhook_events",
                        to="subscriptions.emaildelivery",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "event_type", "processed_at"],
                        name="subscriptions_webhook_type_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "event_id"), name="subscriptions_unique_provider_event"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="emailoutbox",
            index=models.Index(
                fields=["status", "available_at", "created_at", "id"], name="subs_outbox_worker_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("audience_cutoff__isnull", True),
                        ("credential_version__isnull", False),
                        ("message_type", "confirmation"),
                        ("post__isnull", True),
                        ("subscriber__isnull", False),
                    ),
                    models.Q(
                        ("audience_cutoff__isnull", False),
                        ("credential_version__isnull", True),
                        ("message_type", "publication"),
                        ("post__isnull", False),
                        ("subscriber__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="subscriptions_outbox_message_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("delivered_at__isnull", True),
                        ("processing_at__isnull", True),
                        ("status", "pending"),
                    ),
                    models.Q(
                        ("delivered_at__isnull", True),
                        ("processing_at__isnull", False),
                        ("status", "processing"),
                    ),
                    models.Q(("delivered_at__isnull", False), ("status", "delivered")),
                    models.Q(("delivered_at__isnull", True), ("status", "failed")),
                    _connector="OR",
                ),
                name="subscriptions_outbox_status_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailoutbox",
            constraint=models.UniqueConstraint(
                condition=models.Q(("message_type", "publication")),
                fields=("post",),
                name="subscriptions_one_publication_event_per_post",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildelivery",
            index=models.Index(
                fields=["status", "available_at", "created_at", "id"],
                name="subs_delivery_worker_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildelivery",
            index=models.Index(
                fields=["outbox", "status", "available_at"], name="subs_delivery_outbox_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildelivery",
            constraint=models.UniqueConstraint(
                fields=("outbox", "subscriber"), name="subscriptions_unique_outbox_subscriber"
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("processing_at__isnull", True), ("status", "pending")),
                    models.Q(("processing_at__isnull", False), ("status", "processing")),
                    models.Q(("status__in", ("pending", "processing")), _negated=True),
                    _connector="OR",
                ),
                name="subscriptions_delivery_processing_shape",
            ),
        ),
    ]
