# Generated by Django 5.2.16 on 2026-07-27 18:06

from datetime import timedelta

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.utils.encoding import iri_to_uri


def backfill_immutable_delivery_state(apps, schema_editor):
    EmailDelivery = apps.get_model("subscriptions", "EmailDelivery")
    EmailOutbox = apps.get_model("subscriptions", "EmailOutbox")
    EmailWebhookEvent = apps.get_model("subscriptions", "EmailWebhookEvent")

    site_url = settings.PUBLIC_SITE_URL.rstrip("/")
    from_email = settings.RESEND_FROM_EMAIL
    for event in EmailOutbox.objects.select_related("post").iterator():
        event.message_schema_version = 1
        event.snapshot_from_email = from_email
        event.snapshot_site_url = site_url
        if event.message_type == "confirmation":
            event.snapshot_subject = "Confirm your subscription to Kirill Wynn"
            event.snapshot_post_title = ""
            event.snapshot_post_excerpt = ""
            event.snapshot_post_url = ""
        else:
            post = event.post
            event.snapshot_post_title = post.title
            event.snapshot_post_excerpt = post.excerpt
            event.snapshot_post_url = post.canonical_url or (
                f"{site_url}{iri_to_uri(f'/posts/{post.slug}')}"
            )
            event.snapshot_subject = f"New post: {post.title}"
        event.save(
            update_fields=(
                "message_schema_version",
                "snapshot_from_email",
                "snapshot_site_url",
                "snapshot_subject",
                "snapshot_post_title",
                "snapshot_post_excerpt",
                "snapshot_post_url",
            )
        )

    for delivery in EmailDelivery.objects.select_related("subscriber", "outbox").iterator():
        delivery.snapshot_recipient_email = delivery.subscriber.email
        delivery.snapshot_credential_version = (
            delivery.outbox.credential_version
            if delivery.outbox.message_type == "confirmation"
            else delivery.subscriber.unsubscribe_token_version
        )
        delivery.credential_issued_at = delivery.created_at
        if delivery.status in {"pending", "processing"}:
            delivery.status = "manual_review"
            delivery.processing_at = None
            delivery.ambiguity_reason = "payload_mismatch"
            delivery.last_error = "Pre-remediation delivery requires immutable payload review"
        delivery.save(
            update_fields=(
                "snapshot_recipient_email",
                "snapshot_credential_version",
                "credential_issued_at",
                "status",
                "processing_at",
                "ambiguity_reason",
                "last_error",
            )
        )

    retention_seconds = settings.EMAIL_WEBHOOK_RETENTION_SECONDS
    for event in EmailWebhookEvent.objects.select_related("delivery").iterator():
        provider_message_id = (
            event.delivery.provider_message_id if event.delivery_id is not None else None
        )
        if provider_message_id:
            event.processing_state = "applied"
            event.provider_message_id = provider_message_id
        else:
            event.processing_state = "ignored"
            event.delivery_id = None
        event.applied_at = event.processed_at
        event.expires_at = event.processed_at + timedelta(seconds=retention_seconds)
        event.save(
            update_fields=(
                "processing_state",
                "provider_message_id",
                "delivery",
                "applied_at",
                "expires_at",
            )
        )


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_revalidationevent_previous_slug_and_more"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="emailoutbox",
            name="subscriptions_outbox_message_shape",
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="ambiguity_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("transport_failure", "Transport failure"),
                    ("concurrent_request", "Concurrent idempotent request"),
                    ("provider_failure", "Retryable provider failure"),
                    ("window_expired", "Idempotency window expired"),
                    ("payload_mismatch", "Provider payload mismatch"),
                    ("in_flight_cancelled", "Subscriber changed while in flight"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="credential_issued_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="first_provider_attempt_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="last_provider_attempt_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="provider_payload_hash",
            field=models.CharField(
                default="0000000000000000000000000000000000000000000000000000000000000000",
                editable=False,
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="snapshot_credential_version",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="snapshot_recipient_email",
            field=models.CharField(default="migration-pending", editable=False, max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailoutbox",
            name="message_schema_version",
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="emailoutbox",
            name="snapshot_from_email",
            field=models.CharField(default="migration-pending", editable=False, max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailoutbox",
            name="snapshot_post_excerpt",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="emailoutbox",
            name="snapshot_post_title",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="emailoutbox",
            name="snapshot_post_url",
            field=models.CharField(blank=True, editable=False, max_length=2048),
        ),
        migrations.AddField(
            model_name="emailoutbox",
            name="snapshot_site_url",
            field=models.CharField(default="migration-pending", editable=False, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailoutbox",
            name="snapshot_subject",
            field=models.CharField(default="migration-pending", editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailwebhookevent",
            name="applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailwebhookevent",
            name="bounce_type",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="emailwebhookevent",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailwebhookevent",
            name="processing_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending correlation"),
                    ("applied", "Applied"),
                    ("ignored", "Ignored"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="emailwebhookevent",
            name="provider_message_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="emaildelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("sent", "Accepted by provider"),
                    ("delivered", "Delivered"),
                    ("bounced", "Bounced"),
                    ("complained", "Complained"),
                    ("failed", "Terminal failure"),
                    ("skipped", "Skipped"),
                    ("manual_review", "Manual review required"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.RunPython(
            backfill_immutable_delivery_state,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="emaildelivery",
            index=models.Index(
                fields=["status", "first_provider_attempt_at", "id"],
                name="subs_delivery_safety_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailwebhookevent",
            index=models.Index(
                fields=["processing_state", "expires_at", "provider_message_id", "id"],
                name="subs_webhook_pending_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("ambiguity_reason__in", ("", "payload_mismatch")),
                        ("first_provider_attempt_at__isnull", True),
                        ("last_provider_attempt_at__isnull", True),
                    ),
                    models.Q(
                        ("first_provider_attempt_at__isnull", False),
                        (
                            "last_provider_attempt_at__gte",
                            models.F("first_provider_attempt_at"),
                        ),
                        ("last_provider_attempt_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="subscriptions_delivery_attempt_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "manual_review"), _negated=True),
                    models.Q(
                        models.Q(("ambiguity_reason", ""), _negated=True),
                        models.Q(
                            ("first_provider_attempt_at__isnull", False),
                            ("ambiguity_reason", "payload_mismatch"),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="subscriptions_delivery_review_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("snapshot_recipient_email", ""), _negated=True),
                    models.Q(("provider_payload_hash", ""), _negated=True),
                    ("snapshot_credential_version__gte", 1),
                ),
                name="subscriptions_delivery_snapshot_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(
                            ("audience_cutoff__isnull", True),
                            ("credential_version__isnull", False),
                            ("message_type", "confirmation"),
                            ("post__isnull", True),
                            ("snapshot_post_excerpt", ""),
                            ("snapshot_post_title", ""),
                            ("snapshot_post_url", ""),
                            ("subscriber__isnull", False),
                        ),
                        models.Q(
                            ("audience_cutoff__isnull", False),
                            ("credential_version__isnull", True),
                            ("message_type", "publication"),
                            ("post__isnull", False),
                            ("subscriber__isnull", True),
                            models.Q(("snapshot_post_title", ""), _negated=True),
                            models.Q(("snapshot_post_excerpt", ""), _negated=True),
                            models.Q(("snapshot_post_url", ""), _negated=True),
                        ),
                        _connector="OR",
                    ),
                    models.Q(("snapshot_from_email", ""), _negated=True),
                    models.Q(("snapshot_site_url", ""), _negated=True),
                    models.Q(("snapshot_subject", ""), _negated=True),
                ),
                name="subscriptions_outbox_message_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailwebhookevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("applied_at__isnull", True),
                        ("delivery__isnull", True),
                        ("processing_state", "pending"),
                        ("provider_message_id__isnull", False),
                    ),
                    models.Q(
                        ("applied_at__isnull", False),
                        ("delivery__isnull", False),
                        ("processing_state", "applied"),
                        ("provider_message_id__isnull", False),
                    ),
                    models.Q(
                        ("applied_at__isnull", False),
                        ("delivery__isnull", True),
                        ("processing_state", "ignored"),
                    ),
                    _connector="OR",
                ),
                name="subscriptions_webhook_processing_shape",
            ),
        ),
    ]
