# Generated by Django 5.2.16 on 2026-07-27

from django.db import migrations, models

LEGACY_TRANSPORT_IDENTITY = "legacy.unknown"
DOWNGRADE_AMBIGUITY_REASON = "payload_mismatch"
DOWNGRADE_QUARANTINE_ERROR = (
    "Delivery quarantined during downgrade because transport identity was removed"
)
DOWNGRADE_MISMATCH_ERROR = (
    "Transport identity was removed during downgrade; delivery requires review"
)
NEW_TRANSPORT_AMBIGUITY_REASONS = (
    "transport_identity_mismatch",
    "serializer_version_mismatch",
    "idempotency_namespace_mismatch",
    "legacy_transport_identity",
)


def quarantine_legacy_retryable_deliveries(apps, schema_editor):
    EmailDelivery = apps.get_model("subscriptions", "EmailDelivery")
    EmailDelivery.objects.filter(status__in=("pending", "processing")).update(
        status="manual_review",
        processing_at=None,
        ambiguity_reason="legacy_transport_identity",
        last_error="Legacy delivery has no verified provider transport identity",
    )


def prepare_deliveries_for_0002(apps, schema_editor):
    EmailDelivery = apps.get_model("subscriptions", "EmailDelivery")
    EmailDelivery.objects.filter(status__in=("pending", "processing")).update(
        status="manual_review",
        processing_at=None,
        ambiguity_reason=DOWNGRADE_AMBIGUITY_REASON,
        last_error=DOWNGRADE_QUARANTINE_ERROR,
    )
    EmailDelivery.objects.filter(ambiguity_reason__in=NEW_TRANSPORT_AMBIGUITY_REASONS).update(
        ambiguity_reason=DOWNGRADE_AMBIGUITY_REASON,
        last_error=DOWNGRADE_MISMATCH_ERROR,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_harden_email_delivery"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="emaildelivery",
            name="subscriptions_delivery_attempt_shape",
        ),
        migrations.RemoveConstraint(
            model_name="emaildelivery",
            name="subscriptions_delivery_review_shape",
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="provider_contract_id",
            field=models.CharField(
                default=LEGACY_TRANSPORT_IDENTITY,
                editable=False,
                max_length=128,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="provider_idempotency_namespace",
            field=models.CharField(
                default=LEGACY_TRANSPORT_IDENTITY,
                editable=False,
                max_length=128,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="provider_serializer_version",
            field=models.PositiveSmallIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emaildelivery",
            name="ambiguity_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("transport_failure", "Transport failure"),
                    ("concurrent_request", "Concurrent idempotent request"),
                    ("provider_failure", "Retryable provider failure"),
                    ("window_expired", "Idempotency window expired"),
                    ("payload_mismatch", "Provider payload mismatch"),
                    ("transport_identity_mismatch", "Transport contract mismatch"),
                    (
                        "serializer_version_mismatch",
                        "Serializer contract version mismatch",
                    ),
                    (
                        "idempotency_namespace_mismatch",
                        "Provider idempotency namespace mismatch",
                    ),
                    (
                        "legacy_transport_identity",
                        "Unknown legacy transport identity",
                    ),
                    (
                        "in_flight_cancelled",
                        "Subscriber changed while in flight",
                    ),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.RunPython(
            quarantine_legacy_retryable_deliveries,
            prepare_deliveries_for_0002,
        ),
        migrations.AddConstraint(
            model_name="emaildelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "ambiguity_reason__in",
                            (
                                "",
                                "payload_mismatch",
                                "transport_identity_mismatch",
                                "serializer_version_mismatch",
                                "idempotency_namespace_mismatch",
                                "legacy_transport_identity",
                            ),
                        ),
                        ("first_provider_attempt_at__isnull", True),
                        ("last_provider_attempt_at__isnull", True),
                    ),
                    models.Q(
                        ("first_provider_attempt_at__isnull", False),
                        (
                            "last_provider_attempt_at__gte",
                            models.F("first_provider_attempt_at"),
                        ),
                        ("last_provider_attempt_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="subscriptions_delivery_attempt_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "manual_review"), _negated=True),
                    models.Q(
                        models.Q(("ambiguity_reason", ""), _negated=True),
                        models.Q(
                            ("first_provider_attempt_at__isnull", False),
                            (
                                "ambiguity_reason__in",
                                (
                                    "payload_mismatch",
                                    "transport_identity_mismatch",
                                    "serializer_version_mismatch",
                                    "idempotency_namespace_mismatch",
                                    "legacy_transport_identity",
                                ),
                            ),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="subscriptions_delivery_review_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "provider_contract_id__regex",
                        r"^[a-z0-9][a-z0-9._:/-]{0,127}$",
                    ),
                    ("provider_serializer_version__gte", 1),
                    ("provider_serializer_version__lte", 32767),
                    (
                        "provider_idempotency_namespace__regex",
                        r"^[a-z0-9][a-z0-9._:/-]{0,127}$",
                    ),
                ),
                name="subs_delivery_transport_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ("pending", "processing")), _negated=True),
                    models.Q(
                        models.Q(
                            ("provider_contract_id", LEGACY_TRANSPORT_IDENTITY),
                            _negated=True,
                        ),
                        models.Q(
                            (
                                "provider_idempotency_namespace",
                                LEGACY_TRANSPORT_IDENTITY,
                            ),
                            _negated=True,
                        ),
                    ),
                    _connector="OR",
                ),
                name="subs_delivery_retry_identity",
            ),
        ),
    ]
