# Generated by Django 5.2.16 on 2026-07-31

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


def backfill_publication_decisions(apps, schema_editor):
    BlogPostPage = apps.get_model("blog", "BlogPostPage")
    EmailOutbox = apps.get_model("subscriptions", "EmailOutbox")
    PostPublicationEmailDecision = apps.get_model(
        "subscriptions",
        "PostPublicationEmailDecision",
    )

    publication_events = {
        event.post_id: event
        for event in EmailOutbox.objects.filter(
            message_type="publication",
            post_id__isnull=False,
        ).order_by("created_at", "pk")
    }
    migrated_at = timezone.now()
    decisions = []
    for post in BlogPostPage.objects.all().iterator():
        event = publication_events.get(post.pk)
        if event is not None:
            state = "queued"
            decided_at = event.audience_cutoff or event.created_at or post.first_published_at
            outbox_id = event.pk
        elif post.first_published_at is not None:
            state = "suppressed"
            decided_at = post.first_published_at
            outbox_id = None
        else:
            state = "pending"
            decided_at = None
            outbox_id = None

        decisions.append(
            PostPublicationEmailDecision(
                post_id=post.pk,
                state=state,
                decided_at=decided_at,
                outbox_id=outbox_id,
                created_at=migrated_at,
                updated_at=migrated_at,
            )
        )

    PostPublicationEmailDecision.objects.bulk_create(decisions, batch_size=500)


def remove_publication_decisions(apps, schema_editor):
    PostPublicationEmailDecision = apps.get_model(
        "subscriptions",
        "PostPublicationEmailDecision",
    )
    PostPublicationEmailDecision.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_streamfield_chooser_metadata"),
        ("subscriptions", "0003_bind_delivery_transport_identity"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostPublicationEmailDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending first public publication"),
                            ("queued", "Notification queued"),
                            ("suppressed", "Notification suppressed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outbox",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_decision",
                        to="subscriptions.emailoutbox",
                    ),
                ),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_email_decision",
                        to="blog.blogpostpage",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            Q(
                                state="pending",
                                decided_at__isnull=True,
                                outbox__isnull=True,
                            )
                            | Q(
                                state="queued",
                                decided_at__isnull=False,
                                outbox__isnull=False,
                            )
                            | Q(
                                state="suppressed",
                                decided_at__isnull=False,
                                outbox__isnull=True,
                            )
                        ),
                        name="subscriptions_publication_decision_shape",
                    )
                ],
            },
        ),
        migrations.RunPython(
            backfill_publication_decisions,
            remove_publication_decisions,
        ),
    ]
