# Generated by Django 5.2.16 on 2026-07-26 16:23

import django.core.validators
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog index",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogPostPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        help_text="Required plain-text summary used in feeds and metadata fallbacks.",
                        max_length=320,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("rich_text", 0),
                            ("heading", 3),
                            ("image", 4),
                            ("gallery", 5),
                            ("quote", 8),
                            ("bulleted_list", 10),
                            ("numbered_list", 11),
                            ("checklist", 14),
                            ("inline_code", 15),
                            ("code_block", 18),
                            ("table", 19),
                            ("horizontal_divider", 20),
                            ("link", 23),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link"]},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Heading 2"),
                                        ("h3", "Heading 3"),
                                        ("h4", "Heading 4"),
                                    ]
                                },
                            ),
                            2: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                            3: ("wagtail.blocks.StructBlock", [[("level", 1), ("text", 2)]], {}),
                            4: ("wagtail.images.blocks.ImageBlock", [], {}),
                            5: ("wagtail.blocks.ListBlock", (4,), {"max_num": 12, "min_num": 2}),
                            6: ("wagtail.blocks.TextBlock", (), {"max_length": 2000, "rows": 3}),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 200, "required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 6), ("attribution", 7)]],
                                {},
                            ),
                            9: ("wagtail.blocks.CharBlock", (), {"max_length": 500}),
                            10: (
                                "wagtail.blocks.ListBlock",
                                (9,),
                                {"label": "Bulleted list", "min_num": 1},
                            ),
                            11: (
                                "wagtail.blocks.ListBlock",
                                (9,),
                                {"label": "Numbered list", "min_num": 1},
                            ),
                            12: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"default": False, "required": False},
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 9), ("checked", 12)]],
                                {},
                            ),
                            14: ("wagtail.blocks.ListBlock", (13,), {"min_num": 1}),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"icon": "code", "max_length": 500},
                            ),
                            16: (
                                "apps.blog.blocks.LanguageIdentifierBlock",
                                (),
                                {
                                    "help_text": "Lowercase language identifier used by a future syntax highlighter."
                                },
                            ),
                            17: ("wagtail.blocks.TextBlock", (), {"rows": 12}),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 16), ("code", 17)]],
                                {},
                            ),
                            19: (
                                "wagtail.contrib.table_block.blocks.TableBlock",
                                (),
                                {
                                    "table_options": {
                                        "minSpareRows": 0,
                                        "startCols": 3,
                                        "startRows": 3,
                                    }
                                },
                            ),
                            20: (
                                "wagtail.blocks.static_block.StaticBlock",
                                (),
                                {"admin_text": "A horizontal divider.", "icon": "horizontalrule"},
                            ),
                            21: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                            22: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "max_length": 2048,
                                    "required": False,
                                    "validators": [
                                        django.core.validators.URLValidator(
                                            schemes=["http", "https"]
                                        )
                                    ],
                                },
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 2), ("internal_page", 21), ("external_url", 22)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional absolute canonical URL. Defaults to this page's public URL.",
                        max_length=2048,
                        validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
                    ),
                ),
                (
                    "open_graph_title",
                    models.CharField(
                        blank=True,
                        help_text="Defaults to SEO title, then page title.",
                        max_length=70,
                    ),
                ),
                (
                    "open_graph_description",
                    models.CharField(
                        blank=True,
                        help_text="Defaults to search description, then excerpt.",
                        max_length=200,
                    ),
                ),
                (
                    "open_graph_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional social image. Defaults to the first body or gallery image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog post",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogPostTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="blog.blogpostpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blogpostpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="blog.BlogPostTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddConstraint(
            model_name="blogposttag",
            constraint=models.UniqueConstraint(
                fields=("content_object", "tag"), name="unique_blog_post_tag"
            ),
        ),
    ]
