# Generated by Django 5.2.16 on 2026-07-26 16:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevalidationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("updated", "Updated"),
                            ("unpublished", "Unpublished"),
                            ("expired", "Expired"),
                        ],
                        max_length=16,
                    ),
                ),
                ("page_id", models.PositiveBigIntegerField()),
                ("slug", models.SlugField(max_length=255)),
                ("previous_slug", models.SlugField(blank=True, max_length=255)),
                ("occurred_at", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(fields=["state", "created_at"], name="blog_reval_pending_idx"),
                    models.Index(fields=["page_id", "created_at"], name="blog_reval_page_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PreviewSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("credential_digest", models.CharField(editable=False, max_length=64, unique=True)),
                ("page_id", models.PositiveBigIntegerField()),
                ("content_json", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at"], name="blog_preview_created_idx"),
                    models.Index(fields=["content_type", "page_id"], name="blog_preview_page_idx"),
                ],
            },
        ),
    ]
