# Generated by Django 5.2.16 on 2026-07-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_revalidationevent_previewsnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revalidationevent",
            name="previous_slug",
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="revalidationevent",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=255),
        ),
    ]
