# Generated by Django 5.2.16 on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_revalidationevent_previous_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostpage",
            name="notify_subscribers_on_first_publication",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Keep this selected for a new post. Clear it for an archive import. "
                    "The choice is locked when the post first becomes public."
                ),
                verbose_name="Notify subscribers on first publication",
            ),
        ),
        migrations.AddField(
            model_name="blogpostpage",
            name="original_published_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "For archived material, enter when it was first published elsewhere. "
                    "Leave this blank for new material. Wagtail scheduling is controlled "
                    "separately in Publishing schedule."
                ),
                null=True,
                verbose_name="Original publication date",
            ),
        ),
    ]
