# Generated by Django 5.2.16 on 2026-07-31

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_stage15_editorial_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("heading", 3),
                    ("image", 4),
                    ("gallery", 6),
                    ("quote", 9),
                    ("bulleted_list", 11),
                    ("numbered_list", 12),
                    ("checklist", 15),
                    ("inline_code", 16),
                    ("code_block", 19),
                    ("table", 20),
                    ("horizontal_divider", 21),
                    ("link", 24),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "description": "Paragraphs with bold, italic, and links.",
                            "features": ["bold", "italic", "link"],
                            "group": "Text",
                            "label": "Rich text",
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                            ]
                        },
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("level", 1), ("text", 2)]],
                        {
                            "description": "A section heading at level 2, 3, or 4.",
                            "group": "Text",
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "description": "One image with contextual alt text.",
                            "group": "Media",
                        },
                    ),
                    5: ("wagtail.images.blocks.ImageBlock", [], {}),
                    6: (
                        "wagtail.blocks.ListBlock",
                        (5,),
                        {
                            "description": "A gallery of 2–12 images.",
                            "group": "Media",
                            "label": "Gallery",
                            "max_num": 12,
                            "min_num": 2,
                        },
                    ),
                    7: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"max_length": 2000, "rows": 3},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("attribution", 8)]],
                        {
                            "description": "A quotation with optional attribution.",
                            "group": "Text",
                        },
                    ),
                    10: ("wagtail.blocks.CharBlock", (), {"max_length": 500}),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {
                            "description": "An unordered list of short items.",
                            "group": "Lists",
                            "label": "Bulleted list",
                            "min_num": 1,
                        },
                    ),
                    12: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {
                            "description": "An ordered list of short items.",
                            "group": "Lists",
                            "label": "Numbered list",
                            "min_num": 1,
                        },
                    ),
                    13: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 10), ("checked", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ListBlock",
                        (14,),
                        {
                            "description": "Items with checked or unchecked state.",
                            "group": "Lists",
                            "label": "Checklist",
                            "min_num": 1,
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "description": "A short code fragment shown inline.",
                            "group": "Code / Data",
                            "icon": "code",
                            "label": "Inline code",
                            "max_length": 500,
                        },
                    ),
                    17: (
                        "apps.blog.blocks.LanguageIdentifierBlock",
                        (),
                        {
                            "help_text": (
                                "Lowercase language identifier used by a future syntax highlighter."
                            )
                        },
                    ),
                    18: ("wagtail.blocks.TextBlock", (), {"rows": 12}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 17), ("code", 18)]],
                        {
                            "description": "A multiline code sample with a language.",
                            "group": "Code / Data",
                        },
                    ),
                    20: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "description": ("Structured rows and columns with optional headers."),
                            "group": "Code / Data",
                            "label": "Table",
                            "table_options": {
                                "minSpareRows": 0,
                                "startCols": 3,
                                "startRows": 3,
                            },
                        },
                    ),
                    21: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "A horizontal divider.",
                            "description": "A visual break between sections.",
                            "group": "Structure",
                            "icon": "horizontalrule",
                            "label": "Horizontal divider",
                        },
                    ),
                    22: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    23: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "max_length": 2048,
                            "required": False,
                            "validators": [
                                django.core.validators.URLValidator(schemes=["http", "https"])
                            ],
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 2),
                                ("internal_page", 22),
                                ("external_url", 23),
                            ]
                        ],
                        {
                            "description": ("A labelled link to a page or external URL."),
                            "group": "Structure",
                        },
                    ),
                },
            ),
        ),
    ]
