# Generated by Django 5.2.16 on 2026-07-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blog", "0003_alter_revalidationevent_previous_slug_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=5000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "moderation_state",
                    models.CharField(
                        choices=[("visible", "Visible"), ("hidden", "Hidden")],
                        default="visible",
                        max_length=16,
                    ),
                ),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                ("moderation_reason", models.CharField(blank=True, max_length=500)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moderated_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to="blog.blogpostpage",
                    ),
                ),
                (
                    "reply_to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comment_mentions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread_root",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_replies",
                        to="discussions.comment",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["post", "thread_root", "-created_at", "-id"],
                        name="discussion_post_roots_idx",
                    ),
                    models.Index(
                        fields=["thread_root", "created_at", "id"],
                        name="discussion_thread_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("thread_root__isnull", True),
                            models.Q(("thread_root", models.F("id")), _negated=True),
                            _connector="OR",
                        ),
                        name="discussion_no_self_thread_root",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("reply_to_user__isnull", False),
                                ("thread_root__isnull", False),
                            ),
                            models.Q(
                                ("reply_to_user__isnull", True),
                                ("thread_root__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="discussion_reply_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("moderated_at__isnull", True),
                                ("moderated_by__isnull", True),
                                ("moderation_state", "visible"),
                            ),
                            models.Q(
                                ("moderated_at__isnull", False),
                                ("moderated_by__isnull", False),
                                ("moderation_state", "hidden"),
                            ),
                            _connector="OR",
                        ),
                        name="discussion_moderation_shape",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommentRateLimitBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("create", "Create or reply"), ("mutation", "Edit or delete")],
                        max_length=16,
                    ),
                ),
                ("window_started_at", models.DateTimeField()),
                ("request_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_rate_limit_buckets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "scope"),
                        name="discussion_unique_rate_bucket",
                    )
                ],
            },
        ),
    ]
