# Generated by Django 5.2.16 on 2026-07-29 22:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

LEGACY_EMOJI_TO_CATALOG_ID = {}


def map_approved_legacy_reactions(apps, schema_editor):
    """Only explicit, reviewed mappings may bridge legacy Unicode identities."""
    if not LEGACY_EMOJI_TO_CATALOG_ID:
        return
    for model_name in ("PostReaction", "CommentReaction"):
        model = apps.get_model("discussions", model_name)
        for emoji, catalog_id in LEGACY_EMOJI_TO_CATALOG_ID.items():
            model.objects.filter(emoji=emoji, catalog_item__isnull=True).update(
                emoji="",
                catalog_item_id=catalog_id,
            )


def unmap_approved_legacy_reactions(apps, schema_editor):
    if not LEGACY_EMOJI_TO_CATALOG_ID:
        return
    for model_name in ("PostReaction", "CommentReaction"):
        model = apps.get_model("discussions", model_name)
        for emoji, catalog_id in LEGACY_EMOJI_TO_CATALOG_ID.items():
            model.objects.filter(emoji="", catalog_item_id=catalog_id).update(
                emoji=emoji,
                catalog_item=None,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_revalidationevent_previous_slug_and_more"),
        ("discussions", "0002_reactionratelimitbucket_reactionsettings_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentreaction",
            name="emoji",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="postreaction",
            name="emoji",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.CreateModel(
            name="ReactionCatalogItem",
            fields=[
                (
                    "catalog_id",
                    models.SlugField(
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use lowercase ASCII letters, numbers, and single hyphens.",
                                regex="^[a-z0-9]+(?:-[a-z0-9]+)*$",
                            )
                        ],
                    ),
                ),
                ("display_name", models.CharField(max_length=120)),
                ("accessibility_label", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[("static", "Static"), ("animated", "Animated")], max_length=16
                    ),
                ),
                ("ordering", models.PositiveIntegerField(unique=True)),
                ("enabled", models.BooleanField(default=False)),
                ("selectable", models.BooleanField(default=False)),
                (
                    "quick_order",
                    models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "source_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase SHA-256 digest.", regex="^[0-9a-f]{64}$"
                            )
                        ],
                    ),
                ),
                (
                    "normalized_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase SHA-256 digest.", regex="^[0-9a-f]{64}$"
                            )
                        ],
                    ),
                ),
                (
                    "poster_sha256",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase SHA-256 digest.", regex="^[0-9a-f]{64}$"
                            )
                        ],
                    ),
                ),
                (
                    "immutable_asset_version",
                    models.CharField(
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Asset versions must be an immutable sha256-<digest> value.",
                                regex="^sha256-[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("intrinsic_width", models.PositiveSmallIntegerField()),
                ("intrinsic_height", models.PositiveSmallIntegerField()),
                ("frame_count", models.PositiveSmallIntegerField()),
                ("duration_ms", models.PositiveIntegerField()),
                ("minimum_frame_delay_ms", models.PositiveIntegerField()),
                (
                    "asset_storage_key",
                    models.CharField(
                        max_length=320,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use a content-addressed reaction storage key.",
                                regex="^reactions/[a-z0-9]+(?:-[a-z0-9]+)*/[0-9a-f]{64}/(?:asset\\.webp|animation\\.gif|poster\\.webp)$",
                            )
                        ],
                    ),
                ),
                (
                    "poster_storage_key",
                    models.CharField(
                        blank=True,
                        max_length=320,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use a content-addressed reaction storage key.",
                                regex="^reactions/[a-z0-9]+(?:-[a-z0-9]+)*/[0-9a-f]{64}/(?:asset\\.webp|animation\\.gif|poster\\.webp)$",
                            )
                        ],
                    ),
                ),
                ("provenance_source", models.CharField(max_length=500)),
                ("provenance_author", models.CharField(blank=True, max_length=200)),
                ("license", models.CharField(blank=True, max_length=200)),
                ("rights_basis", models.CharField(max_length=500)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("staging-only/unverified", "Staging only / unverified"),
                            ("production-approved", "Production approved"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "manifest_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase SHA-256 digest.", regex="^[0-9a-f]{64}$"
                            )
                        ],
                    ),
                ),
                ("imported_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("ordering", "catalog_id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("intrinsic_height__lte", 512), ("intrinsic_width__lte", 512)
                        ),
                        name="discussion_catalog_dimensions",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("frame_count__gte", 1), ("frame_count__lte", 160)),
                        name="discussion_catalog_frame_count",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("duration_ms__lte", 10000)),
                        name="discussion_catalog_duration",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quick_order__isnull", True),
                            models.Q(("quick_order__gte", 1), ("quick_order__lte", 3)),
                            _connector="OR",
                        ),
                        name="discussion_catalog_quick_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("selectable", False), ("enabled", True), _connector="OR"
                        ),
                        name="discussion_catalog_selectable_enabled",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quick_order__isnull", True),
                            models.Q(("enabled", True), ("selectable", True)),
                            _connector="OR",
                        ),
                        name="discussion_catalog_quick_selectable",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("duration_ms", 0),
                                ("frame_count", 1),
                                ("kind", "static"),
                                ("minimum_frame_delay_ms", 0),
                                ("poster_sha256", ""),
                                ("poster_storage_key", ""),
                            ),
                            models.Q(
                                ("duration_ms__gt", 0),
                                ("frame_count__gte", 2),
                                ("kind", "animated"),
                                ("minimum_frame_delay_ms__gt", 0),
                            ),
                            _connector="OR",
                        ),
                        name="discussion_catalog_kind_metadata",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="commentreaction",
            name="catalog_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="discussions.reactioncatalogitem",
            ),
        ),
        migrations.AddField(
            model_name="postreaction",
            name="catalog_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="discussions.reactioncatalogitem",
            ),
        ),
        migrations.AddField(
            model_name="reactionsettings",
            name="quick_reaction_item_one",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="discussions.reactioncatalogitem",
            ),
        ),
        migrations.AddField(
            model_name="reactionsettings",
            name="quick_reaction_item_three",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="discussions.reactioncatalogitem",
            ),
        ),
        migrations.AddField(
            model_name="reactionsettings",
            name="quick_reaction_item_two",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="discussions.reactioncatalogitem",
            ),
        ),
        migrations.RunPython(
            map_approved_legacy_reactions,
            unmap_approved_legacy_reactions,
        ),
        migrations.AddIndex(
            model_name="commentreaction",
            index=models.Index(
                fields=["comment", "catalog_item", "created_at", "id"],
                name="discuss_comment_catalog_react",
            ),
        ),
        migrations.AddIndex(
            model_name="postreaction",
            index=models.Index(
                fields=["post", "catalog_item", "created_at", "id"],
                name="discuss_post_catalog_react",
            ),
        ),
        migrations.AddConstraint(
            model_name="commentreaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("catalog_item__isnull", False)),
                fields=("comment", "user", "catalog_item"),
                name="discussion_unique_comment_catalog_reaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="commentreaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("catalog_item__isnull", False), ("emoji", "")),
                    models.Q(
                        models.Q(("emoji", ""), _negated=True), ("catalog_item__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="discussion_comment_reaction_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="postreaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("catalog_item__isnull", False)),
                fields=("post", "user", "catalog_item"),
                name="discussion_unique_post_catalog_reaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="postreaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("catalog_item__isnull", False), ("emoji", "")),
                    models.Q(
                        models.Q(("emoji", ""), _negated=True), ("catalog_item__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="discussion_post_reaction_identity",
            ),
        ),
    ]
