# Generated by Django 5.2.16 on 2026-07-30 06:38

from django.conf import settings
from django.db import migrations, models


def activate_catalog_uniqueness(apps, schema_editor):
    specifications = (
        (
            "CommentReaction",
            ("comment", "user", "emoji"),
            "discussion_unique_comment_reaction",
        ),
        (
            "PostReaction",
            ("post", "user", "emoji"),
            "discussion_unique_post_reaction",
        ),
    )
    for model_name, fields, name in specifications:
        model = apps.get_model("discussions", model_name)
        previous = next(
            constraint for constraint in model._meta.constraints if constraint.name == name
        )
        if schema_editor.connection.vendor == "postgresql":
            table = schema_editor.quote_name(model._meta.db_table)
            quoted_name = schema_editor.quote_name(name)
            schema_editor.execute(f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {quoted_name}")
            schema_editor.execute(f"DROP INDEX IF EXISTS {quoted_name}")
            schema_editor.add_constraint(
                model,
                models.UniqueConstraint(
                    fields=fields,
                    condition=~models.Q(emoji=""),
                    name=name,
                ),
            )
            continue
        previous_constraints = model._meta.constraints
        model._meta.constraints = [
            constraint for constraint in previous_constraints if constraint.name != name
        ]
        try:
            schema_editor.remove_constraint(model, previous)
            schema_editor.add_constraint(
                model,
                models.UniqueConstraint(
                    fields=fields,
                    condition=~models.Q(emoji=""),
                    name=name,
                ),
            )
        finally:
            model._meta.constraints = previous_constraints


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_revalidationevent_previous_slug_and_more"),
        ("discussions", "0003_reaction_catalog_expansion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    activate_catalog_uniqueness,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="commentreaction",
                    name="discussion_unique_comment_reaction",
                ),
                migrations.RemoveConstraint(
                    model_name="postreaction",
                    name="discussion_unique_post_reaction",
                ),
                migrations.AddConstraint(
                    model_name="commentreaction",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("emoji", ""), _negated=True),
                        fields=("comment", "user", "emoji"),
                        name="discussion_unique_comment_reaction",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="postreaction",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("emoji", ""), _negated=True),
                        fields=("post", "user", "emoji"),
                        name="discussion_unique_post_reaction",
                    ),
                ),
            ],
        )
    ]
