# Generated by Django 5.2.16 on 2026-08-01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=320, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="auth_state_version",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="user",
            name="email_normalized",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=320,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname_changed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname_normalized",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=160,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="AuthCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("verify_email", "Verify email"),
                            ("password_reset", "Password reset"),
                        ],
                        max_length=24,
                    ),
                ),
                ("email_normalized", models.CharField(editable=False, max_length=320)),
                ("auth_state_version", models.PositiveIntegerField(editable=False)),
                ("credential_digest", models.CharField(editable=False, max_length=64)),
                ("expires_at", models.DateTimeField(editable=False)),
                ("used_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auth_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["user", "purpose", "created_at"],
                        name="users_auth_cred_user_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "id"],
                        name="users_auth_cred_expiry_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("used_at__isnull", True),
                            ("revoked_at__isnull", True),
                            _connector="OR",
                        ),
                        name="users_auth_cred_single_terminal",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("email_normalized", ""), _negated=True),
                            models.Q(("credential_digest", ""), _negated=True),
                        ),
                        name="users_auth_cred_nonempty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthEmailOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("email_verification", "Account email verification"),
                            ("password_reset", "Account password reset"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "message_schema_version",
                    models.PositiveSmallIntegerField(default=1, editable=False),
                ),
                (
                    "snapshot_recipient_email",
                    models.CharField(editable=False, max_length=320),
                ),
                ("snapshot_from_email", models.CharField(editable=False, max_length=512)),
                ("snapshot_site_url", models.CharField(editable=False, max_length=2048)),
                ("snapshot_subject", models.CharField(editable=False, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("delivered", "Delivered to provider"),
                            ("failed", "Terminal failure"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField()),
                ("processing_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                (
                    "idempotency_key",
                    models.CharField(editable=False, max_length=200, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "credential",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_event",
                        to="users.authcredential",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auth_email_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["status", "available_at", "created_at", "id"],
                        name="users_auth_outbox_worker_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("delivered_at__isnull", True),
                                ("processing_at__isnull", True),
                                ("status", "pending"),
                            ),
                            models.Q(
                                ("delivered_at__isnull", True),
                                ("processing_at__isnull", False),
                                ("status", "processing"),
                            ),
                            models.Q(("delivered_at__isnull", False), ("status", "delivered")),
                            models.Q(("delivered_at__isnull", True), ("status", "failed")),
                            _connector="OR",
                        ),
                        name="users_auth_outbox_status_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("snapshot_recipient_email", ""), _negated=True),
                            models.Q(("snapshot_from_email", ""), _negated=True),
                            models.Q(("snapshot_site_url", ""), _negated=True),
                            models.Q(("snapshot_subject", ""), _negated=True),
                        ),
                        name="users_auth_outbox_snapshot_shape",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthEmailDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Accepted by provider"),
                            ("failed", "Terminal failure"),
                            ("manual_review", "Manual review required"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField()),
                ("processing_at", models.DateTimeField(blank=True, null=True)),
                ("provider_contract_id", models.CharField(editable=False, max_length=128)),
                (
                    "provider_serializer_version",
                    models.PositiveSmallIntegerField(editable=False),
                ),
                (
                    "provider_idempotency_namespace",
                    models.CharField(editable=False, max_length=128),
                ),
                ("provider_payload_hash", models.CharField(editable=False, max_length=64)),
                (
                    "first_provider_attempt_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "last_provider_attempt_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("ambiguity_reason", models.CharField(blank=True, max_length=40)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outbox",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery",
                        to="users.authemailoutbox",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["status", "available_at", "created_at", "id"],
                        name="users_auth_delivery_worker_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("processing_at__isnull", True), ("status", "pending")),
                            models.Q(
                                ("processing_at__isnull", False),
                                ("status", "processing"),
                            ),
                            models.Q(("status__in", ("pending", "processing")), _negated=True),
                            _connector="OR",
                        ),
                        name="users_auth_delivery_processing",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("provider_contract_id", ""), _negated=True),
                            models.Q(("provider_idempotency_namespace", ""), _negated=True),
                            models.Q(("provider_payload_hash", ""), _negated=True),
                        ),
                        name="users_auth_delivery_transport",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthRateLimitBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=40)),
                ("key_digest", models.CharField(editable=False, max_length=64)),
                ("window_started_at", models.DateTimeField()),
                ("request_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scope", "window_started_at"],
                        name="users_auth_rate_window_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "key_digest", "window_started_at"),
                        name="users_auth_rate_bucket_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NicknameHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nickname", models.CharField(max_length=160)),
                (
                    "nickname_normalized",
                    models.CharField(editable=False, max_length=160, unique=True),
                ),
                (
                    "change_kind",
                    models.CharField(
                        choices=[
                            ("backfill", "Migration backfill"),
                            ("initial", "Initial selection"),
                            ("change", "User change"),
                            ("staff_override", "Staff override"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nickname_changes_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nickname_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("claimed_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["user", "claimed_at"],
                        name="users_nick_history_user_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("nickname", ""), _negated=True),
                            models.Q(("nickname_normalized", ""), _negated=True),
                        ),
                        name="users_nick_history_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("actor__isnull", False),
                                ("change_kind", "staff_override"),
                                models.Q(("reason", ""), _negated=True),
                            ),
                            models.Q(("change_kind", "staff_override"), _negated=True),
                            _connector="OR",
                        ),
                        name="users_nick_staff_audit_shape",
                    ),
                ],
            },
        ),
    ]
