"""Manual migration

Revision ID: 69e71e4d5e18
Revises:
Create Date: 2025-03-30 00:06:19.151173
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "69e71e4d5e18"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # IMPORTANT:
    # This migration creates objects in a non-default schema ("posts").
    # New databases won't have that schema by default, so we must create it
    # to keep migrations reproducible from scratch (staging, CI, new prod, etc.).
    op.execute("CREATE SCHEMA IF NOT EXISTS posts")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts_raw_telegram",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_name", sa.Text(), nullable=True),
        sa.Column("channel_username", sa.Text(), nullable=True),
        sa.Column("author_id", sa.BigInteger(), nullable=True),
        sa.Column("author_username", sa.Text(), nullable=True),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("media_type", sa.Text(), nullable=True),
        sa.Column("file_id", sa.Text(), nullable=True),
        sa.Column("file_unique_id", sa.Text(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("mime_type", sa.Text(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("photo", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sticker_emoji", sa.Text(), nullable=True),
        sa.Column("sticker_set_name", sa.Text(), nullable=True),
        sa.Column("is_animated", sa.Boolean(), nullable=True),
        sa.Column("is_video", sa.Boolean(), nullable=True),
        sa.Column("poll_id", sa.Text(), nullable=True),
        sa.Column("poll_question", sa.Text(), nullable=True),
        sa.Column("poll_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("poll_total_voter_count", sa.Integer(), nullable=True),
        sa.Column("poll_is_anonymous", sa.Boolean(), nullable=True),
        sa.Column("poll_is_closed", sa.Boolean(), nullable=True),
        sa.Column("poll_allows_multiple_answers", sa.Boolean(), nullable=True),
        sa.Column("location_latitude", sa.Float(), nullable=True),
        sa.Column("location_longitude", sa.Float(), nullable=True),
        sa.Column("media_links", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_message_id", "channel_id", name="uq_message_channel"),
        schema="posts",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts_raw_telegram", schema="posts")

    # Optional cleanup:
    # We usually do NOT drop the schema automatically because:
    # - other objects may be added into "posts" schema in later migrations
    # - schema ownership/permissions can vary
    # If you are 100% sure the schema is only for this table, you can enable:
    #
    # op.execute("DROP SCHEMA IF EXISTS posts")
    #
    # ### end Alembic commands ###
