import base64
import hashlib
import io
import json
from datetime import UTC, datetime
from pathlib import Path
from types import SimpleNamespace

import pytest
from botocore.exceptions import ClientError
from django.core.exceptions import ValidationError
from django.db import IntegrityError, transaction
from django.db.models.deletion import ProtectedError
from PIL import Image, ImageSequence, PngImagePlugin
from wagtail.models import Site

from apps.discussions import catalog_pipeline
from apps.discussions.catalog_pipeline import (
    CatalogPipelineError,
    PreparedObject,
    S3ReactionObjectStore,
    load_manifest,
    prepare_catalog,
    sync_catalog,
)
from apps.discussions.models import (
    PostReaction,
    ReactionCatalogItem,
    ReactionSettings,
)

pytestmark = pytest.mark.django_db


def sha256(value):
    return hashlib.sha256(value).hexdigest()


def png_bytes(*, size=(16, 16), metadata=False):
    image = Image.new("RGBA", size, (220, 30, 80, 180))
    output = io.BytesIO()
    options = {}
    if metadata:
        info = PngImagePlugin.PngInfo()
        info.add_text("Software", "must disappear")
        info.add_itxt("XML:com.adobe.xmp", "<xmp>must disappear</xmp>")
        options["pnginfo"] = info
    image.save(output, "PNG", **options)
    image.close()
    return output.getvalue()


def webp_bytes(*, size=(16, 16)):
    image = Image.new("RGBA", size, (20, 100, 220, 160))
    output = io.BytesIO()
    image.save(output, "WEBP", lossless=True, method=6, exact=True)
    image.close()
    return output.getvalue()


def gif_bytes(*, delays=(0, 10, 40), size=(16, 16), comment=b"must disappear"):
    frames = [
        Image.new("RGBA", size, (index * 60, 30, 240 - index * 50, 180))
        for index in range(len(delays))
    ]
    output = io.BytesIO()
    frames[0].save(
        output,
        "GIF",
        save_all=True,
        append_images=frames[1:],
        duration=list(delays),
        loop=0,
        disposal=2,
        comment=comment,
    )
    for frame in frames:
        frame.close()
    return output.getvalue()


def manifest_document(specs, *, approval_scope="staging-only/unverified"):
    specs = list(specs)
    while len(specs) < 3:
        index = len(specs) + 1
        specs.append((f"fixture-{index}", f"fixture-{index}.png", png_bytes(), "static"))
    items = []
    for index, (catalog_id, source_path, body, kind) in enumerate(specs, start=1):
        items.append(
            {
                "catalog_id": catalog_id,
                "source_path": source_path,
                "source_sha256": sha256(body),
                "display_name": catalog_id.replace("-", " ").title(),
                "accessibility_label": f"{catalog_id} reaction",
                "kind": kind,
                "ordering": index * 10,
                "enabled": True,
                "selectable": True,
                "quick_order": index if index <= 3 else None,
                "provenance": {
                    "source": "Synthetic test fixture",
                    "author": "Test suite",
                },
                "license": "Synthetic fixture",
                "rights_basis": "Generated by the test suite",
                "approval_status": approval_scope,
                "immutable_asset_version": f"source-sha256-{sha256(body)}",
            }
        )
    return {
        "schema_version": 1,
        "catalog_id": "test-catalog",
        "catalog_version": "test-v1",
        "approval_scope": approval_scope,
        "quick_reactions": [item["catalog_id"] for item in items[:3]],
        "items": items,
    }


def write_manifest(tmp_path, specs, *, approval_scope="staging-only/unverified"):
    source_root = tmp_path / "source"
    source_root.mkdir(parents=True)
    document = manifest_document(specs, approval_scope=approval_scope)
    bodies = {spec[1]: spec[2] for spec in specs}
    for item in document["items"]:
        body = bodies.get(item["source_path"], png_bytes())
        path = source_root / item["source_path"]
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(body)
        item["source_sha256"] = sha256(body)
        item["immutable_asset_version"] = f"source-sha256-{sha256(body)}"
    manifest = tmp_path / "manifest.json"
    manifest.write_text(json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n")
    return manifest, source_root, document


def prepare(tmp_path, specs):
    manifest, source_root, _ = write_manifest(tmp_path, specs)
    output = tmp_path / "prepared"
    attestation_path, digest, attestation = prepare_catalog(
        manifest_path=manifest,
        source_root=source_root,
        output_root=output,
    )
    return manifest, source_root, output, attestation_path, digest, attestation


def test_committed_manifest_is_an_explicit_228_item_staging_allowlist():
    path = Path(__file__).resolve().parents[4] / "docs/reaction-catalog/stage16-staging-v1.json"
    manifest = load_manifest(path)

    assert len(manifest.items) == 228
    assert manifest.approval_scope == "staging-only/unverified"
    assert manifest.quick_reactions == ("pepeclap", "pepehmm", "pepelove")
    assert {item.kind for item in manifest.items} == {"static", "animated"}
    assert sum(item.kind == "static" for item in manifest.items) == 180
    assert sum(item.kind == "animated" for item in manifest.items) == 48
    assert all(item.approval_status == "staging-only/unverified" for item in manifest.items)
    assert all(item.license == "unknown / not supplied" for item in manifest.items)
    assert len({item.source_path for item in manifest.items}) == 228


@pytest.mark.parametrize(
    ("mutation", "message"),
    [
        (lambda document: document["items"][0].pop("provenance"), "missing: provenance"),
        (lambda document: document["items"][0].pop("approval_status"), "approval_status"),
        (
            lambda document: document["items"][0].update(source_path="../escape.png"),
            "traversal-free",
        ),
        (
            lambda document: document["items"][0].update(source_path="/absolute.png"),
            "traversal-free",
        ),
    ],
)
def test_manifest_rejects_missing_gate_fields_and_unsafe_paths(tmp_path, mutation, message):
    manifest, _, document = write_manifest(
        tmp_path, [("first", "first.png", png_bytes(), "static")]
    )
    mutation(document)
    manifest.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n")

    with pytest.raises(CatalogPipelineError, match=message):
        load_manifest(manifest)


def test_prepare_rejects_symlink_and_source_hash_mismatch(tmp_path):
    body = png_bytes()
    manifest, source_root, document = write_manifest(
        tmp_path, [("first", "first.png", body, "static")]
    )
    (source_root / "first.png").write_bytes(png_bytes(size=(15, 15)))
    with pytest.raises(CatalogPipelineError, match="source SHA-256 mismatch"):
        prepare_catalog(
            manifest_path=manifest,
            source_root=source_root,
            output_root=tmp_path / "bad-hash",
        )

    (source_root / "first.png").unlink()
    target = source_root / "actual.png"
    target.write_bytes(body)
    (source_root / "first.png").symlink_to(target)
    document["items"][0]["source_sha256"] = sha256(body)
    manifest.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n")
    with pytest.raises(CatalogPipelineError, match="Symlinks are forbidden"):
        prepare_catalog(
            manifest_path=manifest,
            source_root=source_root,
            output_root=tmp_path / "symlink",
        )


def test_mislabeled_webp_is_detected_by_bytes_and_metadata_is_stripped(tmp_path):
    mislabeled = webp_bytes()
    metadata_png = png_bytes(metadata=True)
    manifest, _, output, attestation_path, _, attestation = prepare(
        tmp_path,
        [
            ("mislabeled", "mislabeled.png", mislabeled, "static"),
            ("metadata", "metadata.png", metadata_png, "static"),
            ("third", "third.png", png_bytes(), "static"),
        ],
    )

    assert load_manifest(manifest).items[0].source_path.endswith(".png")
    assert attestation["items"][0]["detected_source_format"] == "WEBP"
    for item in attestation["items"]:
        asset = attestation_path.parent / item["asset"]["relative_path"]
        with Image.open(asset) as normalized:
            assert normalized.format == "WEBP"
            assert not {str(key).lower() for key in normalized.info}.intersection(
                catalog_pipeline.FORBIDDEN_METADATA
            )
    assert output.exists()


@pytest.mark.parametrize(
    ("body_factory", "message"),
    [
        (lambda: png_bytes()[:-5], "Truncated PNG"),
        (lambda: png_bytes() + b"<script>polyglot</script>", "trailing data"),
        (lambda: webp_bytes()[:-2], "RIFF length"),
        (lambda: gif_bytes()[:-1], "trailer"),
        (lambda: gif_bytes() + b"trailing", "trailing data"),
    ],
)
def test_prepare_rejects_truncated_and_polyglot_containers(tmp_path, body_factory, message):
    body = body_factory()
    suffix = ".gif" if body.startswith(b"GIF") else ".png"
    kind = "animated" if body.startswith(b"GIF") else "static"
    manifest, source_root, _ = write_manifest(tmp_path, [("bad", f"bad{suffix}", body, kind)])

    with pytest.raises(CatalogPipelineError, match=message):
        prepare_catalog(
            manifest_path=manifest,
            source_root=source_root,
            output_root=tmp_path / "prepared",
        )


def test_animation_delays_loop_poster_and_comment_normalization(tmp_path):
    animation = gif_bytes(delays=(0, 10, 40))
    _, _, _, attestation_path, _, attestation = prepare(
        tmp_path,
        [
            ("animated", "animated.gif", animation, "animated"),
            ("second", "second.png", png_bytes(), "static"),
            ("third", "third.png", png_bytes(), "static"),
        ],
    )
    item = attestation["items"][0]
    asset = attestation_path.parent / item["asset"]["relative_path"]
    poster = attestation_path.parent / item["poster"]["relative_path"]

    with Image.open(asset) as normalized:
        delays = [frame.info["duration"] for frame in ImageSequence.Iterator(normalized)]
        assert normalized.info["loop"] == 0
        assert min(delays) >= 20
        assert sum(delays) == item["duration_ms"]
        assert "comment" not in {str(key).lower() for key in normalized.info}
    with Image.open(poster) as normalized_poster:
        assert normalized_poster.format == "WEBP"
        assert getattr(normalized_poster, "n_frames", 1) == 1
    assert item["poster"]["sha256"] == sha256(poster.read_bytes())
    assert item["poster"]["storage_key"].split("/")[2] == item["asset"]["sha256"]


def test_limits_cover_source_output_dimensions_frames_duration_and_decoded_cost(
    tmp_path, monkeypatch
):
    oversized = png_bytes() + b"x" * catalog_pipeline.MAX_SOURCE_BYTES
    manifest, source_root, _ = write_manifest(
        tmp_path / "source-size",
        [("oversized", "oversized.png", oversized, "static")],
    )
    with pytest.raises(CatalogPipelineError, match="source is"):
        prepare_catalog(
            manifest_path=manifest,
            source_root=source_root,
            output_root=tmp_path / "source-size-output",
        )

    too_wide = png_bytes(size=(513, 1))
    manifest, source_root, _ = write_manifest(
        tmp_path / "dimensions",
        [("wide", "wide.png", too_wide, "static")],
    )
    with pytest.raises(CatalogPipelineError, match="dimensions"):
        prepare_catalog(
            manifest_path=manifest,
            source_root=source_root,
            output_root=tmp_path / "dimensions-output",
        )

    animation = gif_bytes(delays=(40, 40, 40), size=(32, 32))
    manifest, source_root, _ = write_manifest(
        tmp_path / "animation-limits",
        [("animated", "animated.gif", animation, "animated")],
    )
    monkeypatch.setattr(catalog_pipeline, "MAX_FRAME_COUNT", 2)
    with pytest.raises(CatalogPipelineError, match="frame count"):
        prepare_catalog(
            manifest_path=manifest,
            source_root=source_root,
            output_root=tmp_path / "frame-output",
        )
    monkeypatch.setattr(catalog_pipeline, "MAX_FRAME_COUNT", 160)
    monkeypatch.setattr(catalog_pipeline, "MAX_DURATION_MS", 100)
    with pytest.raises(CatalogPipelineError, match="duration"):
        prepare_catalog(
            manifest_path=manifest,
            source_root=source_root,
            output_root=tmp_path / "duration-output",
        )
    monkeypatch.setattr(catalog_pipeline, "MAX_DURATION_MS", 10_000)
    monkeypatch.setattr(catalog_pipeline, "MAX_DECODED_RGBA_BYTES", 10_000)
    with pytest.raises(CatalogPipelineError, match="decoded RGBA cost"):
        prepare_catalog(
            manifest_path=manifest,
            source_root=source_root,
            output_root=tmp_path / "decoded-output",
        )
    monkeypatch.setattr(catalog_pipeline, "MAX_DECODED_RGBA_BYTES", 64 * 1024 * 1024)
    monkeypatch.setattr(catalog_pipeline, "MAX_OUTPUT_BYTES", 10)
    with pytest.raises(CatalogPipelineError, match="[Nn]ormalized"):
        prepare_catalog(
            manifest_path=manifest,
            source_root=source_root,
            output_root=tmp_path / "output-limit",
        )


def test_prepare_is_deterministic_idempotent_and_refuses_changed_output(tmp_path):
    specs = [
        ("animated", "animated.gif", gif_bytes(), "animated"),
        ("static", "static.png", png_bytes(metadata=True), "static"),
        ("webp", "webp.png", webp_bytes(), "static"),
    ]
    manifest, source_root, _ = write_manifest(tmp_path, specs)
    first = tmp_path / "first"
    second = tmp_path / "second"
    path_one, digest_one, attestation_one = prepare_catalog(
        manifest_path=manifest,
        source_root=source_root,
        output_root=first,
    )
    path_again, digest_again, _ = prepare_catalog(
        manifest_path=manifest,
        source_root=source_root,
        output_root=first,
    )
    path_two, digest_two, attestation_two = prepare_catalog(
        manifest_path=manifest,
        source_root=source_root,
        output_root=second,
    )

    assert digest_one == digest_again == digest_two
    assert path_one.read_bytes() == path_again.read_bytes() == path_two.read_bytes()
    assert attestation_one == attestation_two
    for item in attestation_one["items"]:
        for label in ("asset", "poster"):
            if item[label]:
                assert (
                    first.joinpath(item[label]["relative_path"]).read_bytes()
                    == second.joinpath(item[label]["relative_path"]).read_bytes()
                )
    object_path = first / attestation_one["items"][0]["asset"]["relative_path"]
    object_path.write_bytes(b"changed")
    with pytest.raises(CatalogPipelineError, match="Refusing to overwrite"):
        prepare_catalog(
            manifest_path=manifest,
            source_root=source_root,
            output_root=first,
        )


class FakeObjectStore:
    def __init__(self, environment="staging"):
        self.environment = environment
        self.prefix = f"{environment}/media"
        self.objects = {}
        self.put_calls = 0

    def put_if_absent(self, item, *, catalog_id, version):
        self.put_calls += 1
        self.objects.setdefault(
            item.storage_key,
            (item.body, item.content_type, item.sha256, catalog_id, version),
        )

    def verify(self, item, *, catalog_id, version):
        assert self.objects[item.storage_key] == (
            item.body,
            item.content_type,
            item.sha256,
            catalog_id,
            version,
        )


def test_sync_uploads_before_activation_is_idempotent_and_production_fails_closed(
    tmp_path, blog_index
):
    manifest, _, _, attestation_path, _, _ = prepare(
        tmp_path,
        [
            ("animated", "animated.gif", gif_bytes(), "animated"),
            ("static", "static.png", png_bytes(), "static"),
            ("webp", "webp.png", webp_bytes(), "static"),
        ],
    )
    imported_at = datetime(2026, 7, 29, tzinfo=UTC)
    store = FakeObjectStore()
    first = sync_catalog(
        manifest_path=manifest,
        attestation_path=attestation_path,
        environment="staging",
        object_store=store,
        imported_at=imported_at,
        activate=True,
    )
    second = sync_catalog(
        manifest_path=manifest,
        attestation_path=attestation_path,
        environment="staging",
        object_store=store,
        imported_at=datetime(2026, 7, 30, tzinfo=UTC),
        activate=True,
    )

    assert first["objects"] == 4
    assert first["created"] == 3
    assert second["created"] == second["updated"] == 0
    assert ReactionCatalogItem.objects.count() == 3
    assert list(
        ReactionCatalogItem.objects.order_by("quick_order").values_list("catalog_id", flat=True)
    ) == ["animated", "static", "webp"]
    settings = ReactionSettings.for_site(Site.objects.get(is_default_site=True))
    assert [item.catalog_id for item in settings.quick_reaction_items] == [
        "animated",
        "static",
        "webp",
    ]
    with pytest.raises(CatalogPipelineError, match="fail-closed"):
        sync_catalog(
            manifest_path=manifest,
            attestation_path=attestation_path,
            environment="production",
            object_store=FakeObjectStore("production"),
            imported_at=imported_at,
            activate=False,
        )


class FakeS3Client:
    def __init__(self):
        self.objects = {}

    def head_object(self, *, Bucket, Key):
        if Key not in self.objects:
            raise ClientError(
                {
                    "Error": {"Code": "404"},
                    "ResponseMetadata": {"HTTPStatusCode": 404},
                },
                "HeadObject",
            )
        value = self.objects[Key]
        return {
            "ContentLength": len(value["Body"]),
            "ContentType": value["ContentType"],
            "CacheControl": value["CacheControl"],
            "Metadata": value["Metadata"],
        }

    def put_object(self, **kwargs):
        key = kwargs["Key"]
        assert kwargs["IfNoneMatch"] == "*"
        assert key not in self.objects
        self.objects[key] = kwargs

    def get_object(self, *, Bucket, Key):
        return {"Body": io.BytesIO(self.objects[Key]["Body"])}


class FakeS3Storage:
    bucket_name = "test-bucket"

    def __init__(self, location):
        self.location = location
        self.client = FakeS3Client()
        self.connection = SimpleNamespace(meta=SimpleNamespace(client=self.client))

    def _normalize_name(self, name):
        return f"{self.location}/{name}"


def test_s3_store_uses_isolated_prefix_immutable_headers_and_checksums():
    body = b"attested bytes"
    digest = sha256(body)
    item = PreparedObject(
        relative_path="objects/reactions/test/" + digest + "/asset.webp",
        storage_key="reactions/test/" + digest + "/asset.webp",
        sha256=digest,
        size=len(body),
        content_type="image/webp",
        body=body,
    )
    storage = FakeS3Storage("staging/media")
    store = S3ReactionObjectStore(storage, environment="staging")
    store.put_if_absent(item, catalog_id="test", version=f"sha256-{digest}")
    store.verify(item, catalog_id="test", version=f"sha256-{digest}")
    uploaded = storage.client.objects[f"staging/media/{item.storage_key}"]

    assert uploaded["ContentType"] == "image/webp"
    assert uploaded["CacheControl"] == "public, max-age=31536000, immutable"
    assert uploaded["Metadata"] == {
        "sha256": digest,
        "catalog-id": "test",
        "asset-version": f"sha256-{digest}",
    }
    assert uploaded["ChecksumSHA256"] == base64.b64encode(bytes.fromhex(digest)).decode()
    store.put_if_absent(item, catalog_id="test", version=f"sha256-{digest}")
    assert len(storage.client.objects) == 1
    with pytest.raises(CatalogPipelineError, match="not isolated"):
        S3ReactionObjectStore(storage, environment="production")


def catalog_item(**overrides):
    digest = sha256(b"catalog item")
    values = {
        "catalog_id": "catalog-item",
        "display_name": "Catalog item",
        "accessibility_label": "Catalog item reaction",
        "kind": "static",
        "ordering": 10,
        "enabled": True,
        "selectable": True,
        "quick_order": None,
        "source_sha256": sha256(b"source"),
        "normalized_sha256": digest,
        "poster_sha256": "",
        "immutable_asset_version": f"sha256-{digest}",
        "intrinsic_width": 16,
        "intrinsic_height": 16,
        "frame_count": 1,
        "duration_ms": 0,
        "minimum_frame_delay_ms": 0,
        "asset_storage_key": f"reactions/catalog-item/{digest}/asset.webp",
        "poster_storage_key": "",
        "provenance_source": "Synthetic",
        "provenance_author": "Tests",
        "license": "Synthetic",
        "rights_basis": "Generated",
        "approval_status": "staging-only/unverified",
        "manifest_sha256": sha256(b"manifest"),
        "imported_at": datetime(2026, 7, 29, tzinfo=UTC),
    }
    values.update(overrides)
    return ReactionCatalogItem(**values)


def test_catalog_model_constraints_reaction_identity_and_protect(public_post, user):
    item = catalog_item()
    item.save()
    reaction = PostReaction.objects.create(
        post=public_post,
        user=user,
        catalog_item=item,
    )
    assert reaction.emoji == ""

    with pytest.raises(IntegrityError):
        with transaction.atomic():
            PostReaction.objects.create(
                post=public_post,
                user=user,
                catalog_item=item,
            )
    with pytest.raises(IntegrityError):
        with transaction.atomic():
            PostReaction.objects.bulk_create(
                [
                    PostReaction(
                        post=public_post,
                        user=user,
                        emoji="",
                        catalog_item=None,
                    )
                ]
            )
    with pytest.raises(ProtectedError):
        item.delete()

    invalid = catalog_item(
        catalog_id="disabled-quick",
        ordering=20,
        enabled=False,
        selectable=False,
        quick_order=1,
    )
    with pytest.raises(ValidationError):
        invalid.full_clean()


def test_reaction_settings_requires_three_distinct_enabled_catalog_items(blog_index):
    items = [
        catalog_item(
            catalog_id=f"item-{index}",
            ordering=index * 10,
            quick_order=None,
            asset_storage_key=(f"reactions/item-{index}/{sha256(b'catalog item')}/asset.webp"),
        )
        for index in (1, 2, 3)
    ]
    for item in items:
        item.save()
    settings = ReactionSettings.for_site(Site.objects.get(is_default_site=True))
    settings.quick_reaction_item_one = items[0]
    settings.quick_reaction_item_two = items[1]
    with pytest.raises(ValidationError, match="exactly three"):
        settings.save()
    settings.quick_reaction_item_three = items[0]
    with pytest.raises(ValidationError, match="distinct"):
        settings.save()
    settings.quick_reaction_item_three = items[2]
    settings.save()
    assert list(
        ReactionCatalogItem.objects.order_by("quick_order").values_list("catalog_id", "quick_order")
    ) == [("item-1", 1), ("item-2", 2), ("item-3", 3)]
